---
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@v4
        with:
          cache: poetry
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
      - name: Install dependencies (Poetry)
        run: poetry install --with=dev
      - name: Install dependencies (Yarn)
        run: yarn
      - name: Lint with mypy
        run: yarn mypy
      - name: Lint with pylint
        run: yarn pylint
      - name: Check spelling
        run: yarn check-spelling
      - name: Check formatting
        run: yarn check-formatting
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
name: QA
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
