name: QA
'on':
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python {% raw %}${{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@v4
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
      - name: install deps
        run: |
          yarn
          yarn install-python-deps
      - name: Lint with mypy
        run: yarn mypy
      - name: Lint with pylint
        run: yarn pylint
      - name: Check spelling
        run: yarn check-spelling
      - name: Check formatting
        run: yarn check-formatting
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
